version: 2

registries:
    maven-github:
        type: maven-repository
        url: https://github-package-registry-mirror.gc.nav.no/cached/maven-release
        username: POSTMAN
        password: PAT

updates:
    - package-ecosystem: docker
      directory: /
      schedule:
          interval: daily
      open-pull-requests-limit: 1
